### PR TITLE
Added the blog form

### PR DESCRIPTION
**Pull request by Harshith2255**
Added the form required to post blog and linked it to the navbar on index.html

### CODE REVIEW

**Comment by Surajbokde** [comment]
@Harshith2255  we don't want postblog.html do your changes in blog.html and do it by today itself and make a pr.
also share the Screenshot in description.

**Comment by Harshith2255** [comment]
But you said you wanted to add the form in the blog section

**Comment by Surajbokde** [comment]
@Harshith2255  it want form in blog section but not in another page 
so make a form in blog.html itself before footer

**Comment by Harshith2255** [comment]
Okay let me see

**Comment by Harshith2255** [comment]
I think it will take time because i am using raw html and css and i did not mention id's for some tags

**Comment by Surajbokde** [comment]
@Harshith2255 how much time u want?
can u make pr by  today itself?

**Comment by Harshith2255** [comment]
I will try to do it by today itself

**Comment by Harshith2255** [comment]
i am unable to make a new pull request

**Comment by Harshith2255** [comment]
new commit has been made in  the same pull request

**Review by Surajbokde — APPROVED** [review]

**Pull request merged**
