### PR TITLE
fixed footer according to  issue #33

### PR DESCRIPTION
**Pull request by abhishekjnvk**

### CODE REVIEW

**Comment by Surajbokde** [comment]
@abhishekjnvk can u plz send ss

**Comment by abhishekjnvk** [comment]
Screenshot from 2020-12-18 23-50-09

**Review by Surajbokde — COMMENTED** [review]
remove news latter and instafeed and add contact us in which mention address(of delhi) and below add icon of facebook ,twitter ,instagram ,linkedin.

**Comment by liveAbhishek** [comment]
Screenshot from 2020-12-19 12-49-15

**Review by Surajbokde — APPROVED** [review]

**Pull request merged**
